### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by AprilTu** [kylereddoch/scriptable#1]
I just ran the script as manual, but came across this problem..
I can't figure out what's wrong.
`2022-04-18 20:54:39: Fetching url: ${url}
2022-04-18 20:54:41: Error on line 162:37: TypeError: undefined is not an object (evaluating 'data.data.categories.map')`

**Comment by kylereddoch** [comment]
Hello! This error is because it can't find the categories json attribute. Did you put in your Wakatime username in the TODO section at the top of the script?

**Comment by AprilTu** [comment]
> Hello! This error is because it can't find the categories json attribute. Did you put in your Wakatime username in the TODO section at the top of the script?

Yes, I have put my username in the TODO section. 
Luckily, I find where's getting wrong. I didn't allow display my coding time publicly before! And after I gave permission, the script works! Thank for your kindly help~
<img width="1304" alt="Screenshot 2022-04-18 at 23 34 04" src="https://user-images.githubusercontent.com/43069696/163833492-d5d4ffb2-50f7-49ee-9609-1795f0d9f488.png">

**Comment by kylereddoch** [comment]
That was going to be my next suggestion: to look at Wakatime settings. Glad you figured it out! Let me know how you like it.
